package com.wisdomhub.agent.dto;

/**
 * Response object for a future Agent chat endpoint.
 *
 * <p>The response keeps model and trace metadata separate from the natural
 * language answer so the frontend can show observability details later without
 * changing the API shape.</p>
 */
public class AgentChatResponse {

    /**
     * Final natural language answer generated by the Agent.
     */
    private String answer;

    /**
     * Unique identifier for one Agent execution.
     */
    private String traceId;

    /**
     * Logical model provider used by the execution.
     */
    private String provider;

    /**
     * Logical model name used by the execution.
     */
    private String model;

    /**
     * Whether the runtime was able to use a configured ChatClient.
     */
    private boolean modelAvailable;

    public AgentChatResponse() {
    }

    public AgentChatResponse(String answer, String traceId, String provider, String model, boolean modelAvailable) {
        this.answer = answer;
        this.traceId = traceId;
        this.provider = provider;
        this.model = model;
        this.modelAvailable = modelAvailable;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public boolean isModelAvailable() {
        return modelAvailable;
    }

    public void setModelAvailable(boolean modelAvailable) {
        this.modelAvailable = modelAvailable;
    }
}
